# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/faraday_middleware/all/faraday_middleware.rbi
#
# faraday_middleware-0.13.1
module Faraday
end
class Faraday::Request < Anonymous_Struct_6
end
class Faraday::Response
end
module FaradayMiddleware
end
class FaradayMiddleware::Mashify < Faraday::Response::Middleware
  def initialize(app = nil, options = nil); end
  def mash_class; end
  def mash_class=(arg0); end
  def parse(body); end
  def self.mash_class; end
  def self.mash_class=(arg0); end
end
class FaradayMiddleware::ResponseMiddleware < Faraday::Middleware
  def call(environment); end
  def initialize(app = nil, options = nil); end
  def parse(body); end
  def parse_response?(env); end
  def preserve_raw?(env); end
  def process_response(env); end
  def process_response_type?(type); end
  def response_type(env); end
  def self.define_parser(parser = nil); end
  def self.inherited(subclass); end
  def self.parser; end
  def self.parser=(arg0); end
end
module FaradayMiddleware::OptionsExtension
  def each; end
  def fetch(key, *args); end
  def preserve_raw; end
  def preserve_raw=(arg0); end
  def to_hash; end
end
class Faraday::RequestOptions < Anonymous_Faraday_Options_1
  include FaradayMiddleware::OptionsExtension
end
class FaradayMiddleware::ParseJson < FaradayMiddleware::ResponseMiddleware
end
class FaradayMiddleware::ParseJson::MimeTypeFix < FaradayMiddleware::ResponseMiddleware
  def first_char(body); end
  def parse_response?(env); end
  def process_response(env); end
end
