version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  open-pull-requests-limit: 10
  reviewers:
  - unasuke
  ignore:
  - dependency-name: faraday
    versions:
    - 1.3.1
  - dependency-name: nio4r
    versions:
    - 2.5.6
  - dependency-name: async
    versions:
    - 1.28.6
    - 1.28.8
